version: '3'
services:

  ### SONARR
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr 
    restart: always
    environment:
      - TZ=${TZ} # Specify a timezone to use
      - PUID=${PUID} # User ID to run as
      - PGID=${GUID} # Group ID to run as
    volumes:
      - ${MEDIA_DATA_DIR}:/data # Location of all your media
      - ${CONFIG_DIR}:/config # Contains all relevant configuration files.
    ports:
      - 8989:8989/tcp # Web UI

  ### RADARR
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: always
    #environment:
    #  - TZ=${TZ} # Specify a timezone to use
    #  - PUID=${PUID} # User ID to run as
    #  - PGID=${GUID} # Group ID to run as
    volumes:
      - ${MEDIA_DATA_DIR}:/data # Location of all your media
      - ${CONFIG_DIR}:/config # Contains all relevant configuration files.
    ports:
      - 7878:7878/tcp # Web UI