version: '3'
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro # host localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker socket for local docker integration
      - ./traefik/settings/traefik.yaml:/traefik.yaml:ro # traefik settings in current directory
      - ./traefik/cert/acme.json:/acme.json # folder to store certs
      - ./traefik/hosts/:/hosts/:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web, websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=production"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_AUTH_TRAEFIK}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"