################################################################
#
# Configuration file for Traefik v2.
#
# kiroru
################################################################

serversTransport:
  insecureSkipVerify: true

################################################################
# Global configuration
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: false


################################################################
# API and dashboard configuration
################################################################

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  insecure: true  # Don't do this in production!



################################################################
# EntryPoints configuration
################################################################

entryPoints:
  web:
    address: ":80"
    # ---- Redirect to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
    # ----

  websecure:
    address: ":443"


################################################################
# Providers configuration
################################################################
providers:
  file:
    directory: /hosts
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock" #local docker
#    endpoint: tcp://10.10.10.10:2375 # local or remote tcp docker demon
    exposedByDefault: false


################################################################
# Certificate Resolver configuration
################################################################

certificatesResolvers:
  staging:
    acme:
      email: i@kiroru.ru
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: i@kiroru.ru
      storage: acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
